compute_environment: LOCAL_MACHINE
debug: false
downcast_bf16: 'no'
enable_cpu_affinity: false
distributed_type: FSDP
main_training_function: main
num_machines: 1
num_processes: 2
same_network: false
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
mixed_precision: bf16
fsdp_config:
  fsdp_cpu_ram_efficient_loading: false
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_offload_params: true
  fsdp_reshard_after_forward: true
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_version: 2